external participant final version

diff --git a/keycloak/jobs/job-import-realm.yaml b/keycloak/jobs/job-import-realm.yaml
--- a/keycloak/jobs/job-import-realm.yaml
+++ b/keycloak/jobs/job-import-realm.yaml
@@ -1,9 +1,14 @@
 apiVersion: v1
 kind: ConfigMap
 metadata:
-  name: keycloak-realm-import
+  name: keycloak-realm-config
 data:
-  realm.json:  |
+  KC_ADMIN_USER: "admin"
+  KC_ADMIN_PASSWORD: "admin"
+  KC_URL: "https://conector3-kc.dataspace.gradiant.org"
+  KC_REALM_ADMIN: "master"
+  KC_CLIENT_ADMIN: "admin-cli"
+  realm.json: |
     {
       "realm": "dataspace",
       "notBefore": 0,
@@ -486,36 +491,7 @@ data:
       "webAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister": false,
       "webAuthnPolicyPasswordlessAcceptableAaguids": [],
       "webAuthnPolicyPasswordlessExtraOrigins": [],
-      "users": [
-        {
-          "id": "f7c1a651-3bf1-452c-b3c6-b6528788bb00",
-          "username": "test",
-          "firstName": "test",
-          "email": "test@test.com",
-          "emailVerified": true,
-          "createdTimestamp": 1759508105725,
-          "enabled": true,
-          "totp": false,
-          "credentials": [
-            {
-              "id": "8aa53b61-38c4-41ab-abc6-5348131de3ed",
-              "type": "password",
-              "userLabel": "My password",
-              "createdDate": 1759508113821,
-              "secretData": "{\"value\":\"FA4GjIxreHsFs2eAe50a6X30tYjov31zCWKlZE5AB54cTcVE5kBgO6e/CW5cF/th9RXs0yB0jZyCwOCiy2r/8g==\",\"salt\":\"pIgCojL7U3UTTqD/BR1zkw==\",\"additionalParameters\":{}}",
-              "credentialData": "{\"hashIterations\":210000,\"algorithm\":\"pbkdf2-sha512\",\"additionalParameters\":{}}"
-            }
-          ],
-          "disableableCredentialTypes": [],
-          "requiredActions": [],
-          "realmRoles": [
-            "edc-admin",
-            "default-roles-gradiant"
-          ],
-          "notBefore": 0,
-          "groups": []
-        }
-      ],
+      "users": [],
       "scopeMappings": [
         {
           "clientScope": "offline_access",
@@ -1396,7 +1372,7 @@ data:
         "referrerPolicy": "no-referrer",
         "xRobotsTag": "none",
         "xFrameOptions": "SAMEORIGIN",
-        "contentSecurityPolicy": "frame-src 'self'; frame-ancestors 'self' {{ .Values.keycloak.realm.frameAncestors }}; object-src 'none';",
+        "contentSecurityPolicy": "frame-src 'self'; frame-ancestors 'self'; object-src 'none';",
         "xXSSProtection": "1; mode=block",
         "strictTransportSecurity": "max-age=31536000; includeSubDomains"
       },
@@ -2266,3 +2242,60 @@ data:
         "policies": []
       }
     }
+
+---
+
+apiVersion: batch/v1
+kind: Job
+metadata:
+  name: keycloak-realm-import-api
+spec:
+  template:
+    spec:
+      restartPolicy: OnFailure
+      containers:
+        - name: realm-importer
+          image: alpine:latest
+          envFrom:
+            - configMapRef:
+                name: keycloak-realm-config
+          command: ["/bin/sh", "-c"]
+          args:
+            - |
+              # Install dependencies
+              apk add --no-cache curl jq sed
+
+              echo "Waiting for Keycloak to be ready at $KC_URL..."
+              until curl -s -f "$KC_URL/health/ready" > /dev/null; do
+                echo "Keycloak is unavailable - waiting..."
+                sleep 5
+              done
+
+              echo "Getting Admin Token..."
+              TOKEN=$(curl -s -X POST "$KC_URL/realms/$KC_REALM_ADMIN/protocol/openid-connect/token"                 -H "Content-Type: application/x-www-form-urlencoded"                 -d "username=$KC_ADMIN_USER"                 -d "password=$KC_ADMIN_PASSWORD"                 -d "grant_type=password"                 -d "client_id=$KC_CLIENT_ADMIN" | jq -r '.access_token')
+
+              if [ "$TOKEN" == "null" ] || [ -z "$TOKEN" ]; then
+                echo "Error obtaining token. Check credentials."
+                exit 1
+              fi
+
+              echo "Sending Realm to the API..."
+              HTTP_CODE=$(curl -s -o /dev/stderr -w "%{http_code}" -X POST "$KC_URL/admin/realms"                 -H "Authorization: Bearer $TOKEN"                 -H "Content-Type: application/json"                 -d @/config/realm.json)
+
+              if [ "$HTTP_CODE" -eq 201 ]; then
+                echo "✅ Realm created successfully!"
+              elif [ "$HTTP_CODE" -eq 409 ]; then
+                echo "⚠️ Realm already exists. Nothing done."
+              else
+                echo "❌ Import failed. HTTP Code: $HTTP_CODE"
+                exit 1
+              fi
+
+          volumeMounts:
+            - name: realm-config-vol
+              mountPath: /config
+              readOnly: true
+      volumes:
+        - name: realm-config-vol
+          configMap:
+            name: keycloak-realm-config
